package com.sparta;

import java.util.Arrays;
import java.util.Scanner;

public class DisplayManager {
    // this is the file that will interact with the user
    Scanner input = new Scanner(System.in);
    SortManager sortManager = new SortManager();
    public void display(){
        String mainMenu = """

                \t\t\t-----MAIN MENU-----

                This program will sort a random array generated by you.
                Please enter the size of the array:\s""";
        System.out.println(mainMenu);
         try {
             int arraySize = input.nextInt();
             int[] randomArray = sortManager.arrayGenerator(arraySize);
             System.out.println("\n\nHere is your array: \n"+ Arrays.toString(randomArray) + "\n\n");
             nextStep(randomArray);
         } catch (ArithmeticException e) {
             System.out.println("Please enter a valid option from the menu");
         } catch (Exception e){
             System.out.println("You need to enter a positive integer.");
         }
    }
    private void nextStep(int[] randomArray) throws ArithmeticException {
        System.out.println("What type of sorting algorithm would you like to use? ");
        System.out.println("Please enter a corresponding number.");
        System.out.println("1: Bubble Sort Algorithm");
        System.out.println("2: Merge Sort Algorithm");
        System.out.println("3: Binary Tree Implementation");
        int pick = input.nextInt();
        if(pick > 0 && pick < 4){
            System.out.println(Arrays.toString(sortManager.pickSort(pick, randomArray)));
        } else {
            throw new ArithmeticException();
        }

    }
}
